Requerimientos 16 y 17 (Consulta de Saldo y Registro de ingreso/egreso de caja)
natir0501/ProyectoAP pull request #104
Opened 2018-11-18 17:52 UTC by natir0501

2018-11-19 23:43 UTC, gabrielarce23 commented on server/routes/cuenta-rutas.js
> +api.put('/cuenta/movimientos/ingresomovimiento', async (req,res) =>{
Usar patch.... /id y esperar el movimiento nuevo.

2018-11-19 23:46 UTC, gabrielarce23 commented on server/routes/cuenta-rutas.js
> +        let idCuenta=req.body._id;
req.body.movimiento

2018-11-19 23:48 UTC, gabrielarce23 commented on server/routes/cuenta-rutas.js
> +        if(tipo==="1"){tipo="Ingreso"}
esta validación no va

2018-11-19 23:50 UTC, gabrielarce23 requested changes
Para cambios

2018-11-20 23:35 UTC, natir0501 commented on server/routes/cuenta-rutas.js
> +api.put('/cuenta/movimientos/ingresomovimiento', async (req,res) =>{
@gabrielarce23 Además del movimiento voy a precisar el Id de la cuenta porque tengo que 1) meter el movimiento en esa cuenta y 2) afectar el saldo de la cuenta. Mandame un objeto así

{
movimiento : {
//acá todo el movimiento (o sea: fecha, monto positivo si es ingreso y negativo si es egreso, tipo string, objectId del concepto, comentario, y obetctId del usuario)
},
idcuenta: objectId de la cuenta.
}

2018-11-20 23:57 UTC, natir0501 commented on server/routes/cuenta-rutas.js
> +api.put('/cuenta/movimientos/ingresomovimiento', async (req,res) =>{
Ignorá el comentario anterior. El id lo tengo en el parametro. Solo preciso el movimiento :)

2018-11-21 22:26 UTC, gabrielarce23 approved these changes

2018-11-21 22:26 UTC, merged